apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    kompose.cmd: kompose convert
#    kompose.version: 1.22.0 (955b78124)
#  creationTimestamp: null
  labels:
    io.kompose.service: todo-web-application
  name: todo-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-web-application
#  strategy: {}
  template:
    metadata:
#      annotations:
#        kompose.cmd: kompose convert
#        kompose.version: 1.22.0 (955b78124)
#      creationTimestamp: null
      labels:
#        io.kompose.network/todo-web-application-network: "true"
        io.kompose.service: todo-web-application
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              value: todos
            - name: RDS_HOSTNAME
              value: mysql
            - name: RDS_PASSWORD
              value: dummy
            - name: RDS_PORT
              value: "3306"
            - name: RDS_USERNAME
              value: todosuser
          image: lalitrnagpal/07-web-mysql-kompose-example:0.0.1-SNAPSHOT
          name: todo-web-application
          ports:
            - containerPort: 8080
#          resources: {}
      restartPolicy: Always
# status: {}